import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "catecismo.db")

def crear_tabla_biblia():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("DROP TABLE IF EXISTS biblia")
    cursor.execute("""
        CREATE TABLE biblia (
            referencia TEXT PRIMARY KEY,
            texto TEXT NOT NULL,
            texto_en TEXT NOT NULL DEFAULT ''
        )
    """)

    # Textos bíblicos RVR1960 para todas las referencias del Catecismo
    textos = {
        # === PREGUNTA 1 ===
        "Romans 14:7-8": "Porque ninguno de nosotros vive para sí, y ninguno muere para sí. Pues si vivimos, para el Señor vivimos; y si morimos, para el Señor morimos. Así pues, sea que vivamos, o que muramos, del Señor somos.",
        "1 Corinthians 6:19-20": "¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros, el cual tenéis de Dios, y que no sois vuestros? Porque habéis sido comprados por precio; glorificad, pues, a Dios en vuestro cuerpo y en vuestro espíritu, los cuales son de Dios.",
        "1 John 3:8": "El que practica el pecado es del diablo; porque el diablo peca desde el principio. Para esto apareció el Hijo de Dios, para deshacer las obras del diablo.",
        "John 10:28": "Y yo les doy vida eterna; y no perecerán jamás, ni nadie las arrebatará de mi mano.",
        "Romans 8:28": "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.",
        "Romans 8:38-39": "Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir, ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro.",

        # === PREGUNTA 2 ===
        "Luke 24:46-47": "Y les dijo: Así está escrito, y así fue necesario que el Cristo padeciese, y resucitase de los muertos al tercer día; y que se predicase en su nombre el arrepentimiento y el perdón de pecados en todas las naciones, comenzando desde Jerusalén.",
        "1 Corinthians 6:11": "Y esto erais algunos; mas ya habéis sido lavados, ya habéis sido santificados, ya habéis sido justificados en el nombre del Señor Jesús, y por el Espíritu de nuestro Dios.",
        "Titus 3:3-7": "Porque nosotros también éramos en otro tiempo insensatos, rebeldes, extraviados, esclavos de concupiscencias y deleites diversos, viviendo en malicia y envidia, aborrecibles, y aborreciéndonos unos a otros. Pero cuando se manifestó la bondad de Dios nuestro Salvador, y su amor para con los hombres, nos salvó, no por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia, por el lavamiento de la regeneración y por la renovación en el Espíritu Santo, el cual derramó en nosotros abundantemente por Jesucristo nuestro Salvador, para que justificados por su gracia, viniésemos a ser herederos conforme a la esperanza de la vida eterna.",
        "Ephesians 5:8-10": "Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz (porque el fruto del Espíritu es en toda bondad, justicia y verdad), comprobando lo que es agradable al Señor.",

        # === PREGUNTA 3 ===
        "Romans 3:20": "Ya que por las obras de la ley ningún ser humano será justificado delante de él; porque por medio de la ley es el conocimiento del pecado.",
        "Romans 7:7": "¿Qué diremos, pues? ¿La ley es pecado? En ninguna manera. Pero yo no conocí el pecado sino por la ley; porque tampoco conociera la codicia, si la ley no dijera: No codiciarás.",
        "Galatians 3:24": "De manera que la ley ha sido nuestro ayo, para llevarnos a Cristo, a fin de que fuésemos justificados por la fe.",

        # === PREGUNTA 4 ===
        "Matthew 22:37-40": "Jesús le dijo: Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente. Este es el primero y grande mandamiento. Y el segundo es semejante: Amarás a tu prójimo como a ti mismo. De estos dos mandamientos depende toda la ley y los profetas.",
        "Deuteronomy 6:5": "Y amarás a Jehová tu Dios de todo tu corazón, y de toda tu alma, y con todas tus fuerzas.",
        "Leviticus 19:18": "No te vengarás, ni guardarás rencor a los hijos de tu pueblo, sino amarás a tu prójimo como a ti mismo. Yo Jehová.",

        # === PREGUNTA 5 ===
        "Romans 3:10-12": "Como está escrito: No hay justo, ni aun uno; no hay quien entienda, no hay quien busque a Dios. Todos se desviaron, a una se hicieron inútiles; no hay quien haga lo bueno, no hay ni siquiera uno.",
        "Genesis 6:5": "Y vio Jehová que la maldad de los hombres era mucha en la tierra, y que todo designio de los pensamientos del corazón de ellos era de continuo solamente el mal.",
        "Romans 8:7": "Por cuanto los designios de la carne son enemistad contra Dios; porque no se sujetan a la ley de Dios, ni tampoco pueden.",
        "Ephesians 2:3": "Entre los cuales también todos nosotros vivimos en otro tiempo en los deseos de nuestra carne, haciendo la voluntad de la carne y de los pensamientos, y éramos por naturaleza hijos de ira, lo mismo que los demás.",

        # === PREGUNTA 6 ===
        "Genesis 1:26-27": "Entonces dijo Dios: Hagamos al hombre a nuestra imagen, conforme a nuestra semejanza; y señoree en los peces del mar, en las aves de los cielos, en las bestias, en toda la tierra, y en todo animal que se arrastra sobre la tierra. Y creó Dios al hombre a su imagen, a imagen de Dios lo creó; varón y hembra los creó.",
        "Ephesians 4:24": "Y vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad.",
        "Colossians 3:10": "Y revestido del nuevo, el cual conforme a la imagen del que lo creó se va renovando hasta el conocimiento pleno.",

        # === PREGUNTA 7 ===
        "Genesis 3:1-7": "Pero la serpiente era astuta, más que todos los animales del campo que Jehová Dios había hecho; la cual dijo a la mujer: ¿Conque Dios os ha dicho: No comáis de todo árbol del huerto? Y la mujer respondió a la serpiente: Del fruto de los árboles del huerto podemos comer; pero del fruto del árbol que está en medio del huerto dijo Dios: No comeréis de él, ni le tocaréis, para que no muráis. Entonces la serpiente dijo a la mujer: No moriréis; sino que sabe Dios que el día que comáis de él, serán abiertos vuestros ojos, y seréis como Dios, sabiendo el bien y el mal.",
        "Romans 5:12": "Por tanto, como el pecado entró en el mundo por un hombre, y por el pecado la muerte, así la muerte pasó a todos los hombres, por cuanto todos pecaron.",
        "Romans 5:18-19": "Así que, como por la transgresión de uno vino la condenación a todos los hombres, de la misma manera por la justicia de uno vino a todos los hombres la justificación de vida. Porque así como por la desobediencia de un hombre los muchos fueron constituidos pecadores, así también por la obediencia de uno, los muchos serán constituidos justos.",

        # === PREGUNTA 8 ===
        "Genesis 8:21": "Y percibió Jehová olor grato; y dijo Jehová en su corazón: No volveré más a maldecir la tierra por causa del hombre; porque el intento del corazón del hombre es malo desde su juventud.",
        "Romans 8:7-8": "Por cuanto los designios de la carne son enemistad contra Dios; porque no se sujetan a la ley de Dios, ni tampoco pueden; y los que viven según la carne no pueden agradar a Dios.",
        "John 3:5-6": "Respondió Jesús: De cierto, de cierto te digo, que el que no naciere de agua y del Espíritu, no puede entrar en el reino de Dios. Lo que es nacido de la carne, carne es; y lo que es nacido del Espíritu, espíritu es.",
        "Ephesians 2:1-5": "Y él os dio vida a vosotros, cuando estabais muertos en vuestros delitos y pecados, en los cuales anduvisteis en otro tiempo, siguiendo la corriente de este mundo. Pero Dios, que es rico en misericordia, por su gran amor con que nos amó, aun estando nosotros muertos en pecados, nos dio vida juntamente con Cristo (por gracia sois salvos).",

        # === PREGUNTA 9 ===
        "Genesis 1:31": "Y vio Dios todo lo que había hecho, y he aquí que era bueno en gran manera.",
        "Ecclesiastes 7:29": "He aquí, solamente esto he hallado: que Dios hizo al hombre recto, pero ellos buscaron muchas perversiones.",
        "Deuteronomy 30:19": "A los cielos y a la tierra llamo por testigos hoy contra vosotros, que os he puesto delante la vida y la muerte, la bendición y la maldición; escoge, pues, la vida, para que vivas tú y tu descendencia.",

        # === PREGUNTA 10 ===
        "Galatians 3:10": "Porque todos los que dependen de las obras de la ley están bajo maldición, pues escrito está: Maldito todo aquel que no permaneciere en todas las cosas escritas en el libro de la ley, para hacerlas.",
        "Deuteronomy 27:26": "Maldito el que no confirmare las palabras de esta ley para hacerlas. Y dirá todo el pueblo: Amén.",
        "Nahum 1:2": "Jehová es Dios celoso y vengador; Jehová es vengador y lleno de indignación; se venga de sus adversarios, y guarda enojo para sus enemigos.",
        "Hebrews 10:31": "¡Horrenda cosa es caer en manos del Dios vivo!",

        # === PREGUNTA 11 ===
        "Exodus 34:6-7": "Y pasando Jehová por delante de él, proclamó: ¡Jehová! ¡Jehová! fuerte, misericordioso y piadoso; tardo para la ira, y grande en misericordia y verdad; que guarda misericordia a millares, que perdona la iniquidad, la rebelión y el pecado, y que de ningún modo tendrá por inocente al malvado.",
        "Exodus 20:5": "No te inclinarás a ellas, ni las honrarás; porque yo soy Jehová tu Dios, fuerte, celoso, que visito la maldad de los padres sobre los hijos hasta la tercera y cuarta generación de los que me aborrecen.",
        "Psalms 5:4-6": "Porque tú no eres un Dios que se complace en la maldad; el malo no habitará junto a ti. Los insensatos no estarán delante de tus ojos; aborreces a todos los que hacen iniquidad. Destruirás a los que hablan mentira; al hombre sanguinario y engañador abominará Jehová.",
        "2 Corinthians 5:10": "Porque es necesario que todos nosotros comparezcamos ante el tribunal de Cristo, para que cada uno reciba según lo que haya hecho mientras estaba en el cuerpo, sea bueno o sea malo.",

        # === PREGUNTAS 12-14 ===
        "Genesis 2:17": "Mas del árbol de la ciencia del bien y del mal no comerás; porque el día que de él comieres, ciertamente morirás.",
        "Romans 8:3-4": "Porque lo que era imposible para la ley, por cuanto era débil por la carne, Dios, enviando a su Hijo en semejanza de carne de pecado y a causa del pecado, condenó al pecado en la carne; para que la justicia de la ley se cumpliese en nosotros, que no andamos conforme a la carne, sino conforme al Espíritu.",
        "Hebrews 2:14-15": "Así que, por cuanto los hijos participaron de carne y sangre, él también participó de lo mismo, para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es, al diablo, y librar a todos los que por el temor de la muerte estaban durante toda la vida sujetos a servidumbre.",
        "Matthew 6:12": "Y perdónanos nuestras deudas, como también nosotros perdonamos a nuestros deudores.",
        "Romans 2:4-5": "¿O menosprecias las riquezas de su benignidad, paciencia y longanimidad, ignorando que su benignidad te guía al arrepentimiento? Pero por tu dureza y por tu corazón no arrepentido, atesoras para ti mismo ira para el día de la ira y de la revelación del justo juicio de Dios.",
        "Isaiah 64:6": "Si bien todos nosotros somos como suciedad, y todas nuestras justicias como trapo de inmundicia; y caímos todos nosotros como la hoja, y nuestras maldades nos llevaron como viento.",
        "Hebrews 2:14-17": "Así que, por cuanto los hijos participaron de carne y sangre, él también participó de lo mismo, para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es, al diablo. Por lo cual debía ser en todo semejante a sus hermanos, para venir a ser misericordioso y fiel sumo sacerdote en lo que a Dios se refiere, para expiar los pecados del pueblo.",
        "1 Peter 3:18": "Porque también Cristo padeció una sola vez por los pecados, el justo por los injustos, para llevarnos a Dios.",
        "Isaiah 53:11": "Verá el fruto de la aflicción de su alma, y quedará satisfecho; por su conocimiento justificará mi siervo justo a muchos, y llevará las iniquidades de ellos.",

        # === PREGUNTAS 15-18 ===
        "Jeremiah 23:5-6": "He aquí que vienen días, dice Jehová, en que levantaré a David renuevo justo, y reinará como Rey, el cual será satisfecho, y hará juicio y justicia en la tierra. En sus días será salvo Judá, e Israel habitará confiado; y este será su nombre con el cual le llamarán: Jehová, justicia nuestra.",
        "1 Timothy 2:5": "Porque hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre.",
        "Luke 2:11": "Que os ha nacido hoy, en la ciudad de David, un Salvador, que es CRISTO el Señor.",
        "Isaiah 9:6": "Porque un niño nos es nacido, hijo nos es dado, y el principado sobre su hombro; y se llamará su nombre Admirable, Consejero, Dios Fuerte, Padre Eterno, Príncipe de Paz.",
        "Hebrews 2:17": "Por lo cual debía ser en todo semejante a sus hermanos, para venir a ser misericordioso y fiel sumo sacerdote en lo que a Dios se refiere, para expiar los pecados del pueblo.",
        "Romans 5:19": "Porque así como por la desobediencia de un hombre los muchos fueron constituidos pecadores, así también por la obediencia de uno, los muchos serán constituidos justos.",
        "1 Corinthians 15:21": "Porque por cuanto la muerte entró por un hombre, también por un hombre la resurrección de los muertos.",
        "Isaiah 53:4-5": "Ciertamente llevó él nuestras enfermedades, y sufrió nuestros dolores; y nosotros le tuvimos por azotado, por herido de Dios y abatido. Mas él herido fue por nuestras rebeliones, molido por nuestros pecados; el castigo de nuestra paz fue sobre él, y por su llaga fuimos nosotros curados.",
        "Acts 2:24": "Al cual Dios levantó, sueltos los dolores de la muerte, por cuanto era imposible que fuese retenido por ella.",
        "John 3:16": "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.",
        "1 John 4:9": "En esto se mostró el amor de Dios para con nosotros, en que Dios envió a su Hijo unigénito al mundo, para que vivamos por él.",
        "1 Corinthians 1:30": "Mas por él estáis vosotros en Cristo Jesús, el cual nos ha sido hecho por Dios sabiduría, justificación, santificación y redención.",
        "1 Timothy 2:5-6": "Porque hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre, el cual se dio a sí mismo en rescate por todos, de lo cual se dio testimonio a su debido tiempo.",
        "Matthew 1:21": "Y dará a luz un hijo, y llamarás su nombre JESÚS, porque él salvará a su pueblo de sus pecados.",
        "Isaiah 7:14": "Por tanto, el Señor mismo os dará señal: He aquí que la virgen concebirá, y dará a luz un hijo, y llamará su nombre Emanuel.",

        # === PREGUNTA 19 ===
        "Genesis 3:15": "Y pondré enemistad entre ti y la mujer, y entre tu simiente y la simiente suya; ésta te herirá en la cabeza, y tú le herirás en el calcañar.",
        "Genesis 22:18": "En tu simiente serán benditas todas las naciones de la tierra, por cuanto obedeciste a mi voz.",
        "Romans 1:2": "Que él había prometido antes por sus profetas en las santas Escrituras.",
        "Hebrews 1:1-2": "Dios, habiendo hablado muchas veces y de muchas maneras en otro tiempo a los padres por los profetas, en estos postreros días nos ha hablado por el Hijo, a quien constituyó heredero de todo, y por quien asimismo hizo el universo.",
        "Acts 3:22-24": "Porque Moisés dijo a los padres: El Señor vuestro Dios os levantará profeta de entre vuestros hermanos, como a mí; a él oiréis en todas las cosas que os hable.",

        # === PREGUNTAS 20-21 ===
        "Romans 5:17-19": "Pues si por la transgresión de uno solo reinó la muerte, mucho más reinarán en vida por uno solo, Jesucristo, los que reciben la abundancia de la gracia y del don de la justicia.",
        "John 1:12-13": "Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios; los cuales no son engendrados de sangre, ni de voluntad de carne, ni de voluntad de varón, sino de Dios.",
        "Matthew 7:14": "Porque estrecha es la puerta, y angosto el camino que lleva a la vida, y pocos son los que la hallan.",
        "James 2:19": "Tú crees que Dios es uno; bien haces. También los demonios creen, y tiemblan.",
        "Hebrews 11:1": "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.",
        "Romans 4:20-21": "Tampoco dudó, por incredulidad, de la promesa de Dios, sino que se fortaleció en fe, dando gloria a Dios, plenamente convencido de que era también poderoso para hacer todo lo que había prometido.",
        "Ephesians 2:8-9": "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; no por obras, para que nadie se gloríe.",
        "Galatians 2:20": "Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí.",

        # === PREGUNTAS 22-25 ===
        "Matthew 28:19-20": "Por tanto, id, y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo; enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.",
        "Mark 1:15": "Diciendo: El tiempo se ha cumplido, y el reino de Dios se ha acercado; arrepentíos, y creed en el evangelio.",
        "John 20:31": "Pero éstas se han escrito para que creáis que Jesús es el Cristo, el Hijo de Dios, y para que creyendo, tengáis vida en su nombre.",
        "Acts 8:37": "Felipe dijo: Si crees de todo corazón, bien puedes. Y respondiendo, dijo: Creo que Jesucristo es el Hijo de Dios.",
        "1 Corinthians 15:3-4": "Porque primeramente os he enseñado lo que asimismo recibí: Que Cristo murió por nuestros pecados, conforme a las Escrituras; y que fue sepultado, y que resucitó al tercer día, conforme a las Escrituras.",
        "1 Peter 1:18-21": "Sabiendo que fuisteis rescatados de vuestra vana manera de vivir, la cual recibisteis de vuestros padres, no con cosas corruptibles, como oro o plata, sino con la sangre preciosa de Cristo, como de un cordero sin mancha y sin contaminación.",
        "Matthew 28:19": "Por tanto, id, y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo.",
        "Deuteronomy 6:4": "Oye, Israel: Jehová nuestro Dios, Jehová uno es.",
        "1 John 5:7": "Porque tres son los que dan testimonio en el cielo: el Padre, el Verbo y el Espíritu Santo; y estos tres son uno.",
        "2 Corinthians 13:14": "La gracia del Señor Jesucristo, el amor de Dios, y la comunión del Espíritu Santo sean con todos vosotros. Amén.",

        # === PREGUNTAS 26-28 (Providencia) ===
        "Genesis 1:1": "En el principio creó Dios los cielos y la tierra.",
        "Psalms 33:6": "Por la palabra de Jehová fueron hechos los cielos, y todo el ejército de ellos por el aliento de su boca.",
        "Acts 17:28": "Porque en él vivimos, y nos movemos, y somos; como algunos de vuestros propios poetas también han dicho: Porque linaje suyo somos.",
        "Matthew 10:29-30": "¿No se venden dos pajarillos por un cuarto? Con todo, ni uno de ellos cae a tierra sin vuestro Padre. Pues aun vuestros cabellos están todos contados.",
        "Acts 17:25-28": "Ni es honrado por manos de hombres, como si necesitase de algo; pues él es quien da a todos vida y aliento y todas las cosas. Porque en él vivimos, y nos movemos, y somos.",
        "Hebrews 1:3": "El cual, siendo el resplandor de su gloria, y la imagen misma de su sustancia, y quien sustenta todas las cosas con la palabra de su poder.",
        "Jeremiah 23:23-24": "¿Soy yo Dios de cerca solamente, dice Jehová, y no Dios desde lejos? ¿Se ocultará alguno, dice Jehová, en escondrijos que yo no lo vea? ¿No lleno yo, dice Jehová, el cielo y la tierra?",
        "Matthew 10:29": "¿No se venden dos pajarillos por un cuarto? Con todo, ni uno de ellos cae a tierra sin vuestro Padre.",
        "Romans 5:3-5": "Y no sólo esto, sino que también nos gloriamos en las tribulaciones, sabiendo que la tribulación produce paciencia; y la paciencia, prueba; y la prueba, esperanza; y la esperanza no avergüenza; porque el amor de Dios ha sido derramado en nuestros corazones por el Espíritu Santo que nos fue dado.",
        "James 1:3": "Sabiendo que la prueba de vuestra fe produce paciencia.",
        "1 Thessalonians 5:18": "Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.",

        # === PREGUNTAS 29-34 (Sobre Cristo) ===
        "Acts 4:12": "Y en ningún otro hay salvación; porque no hay otro nombre bajo el cielo, dado a los hombres, en que podamos ser salvos.",
        "John 15:4-5": "Permaneced en mí, y yo en vosotros. Como el pámpano no puede llevar fruto por sí mismo, si no permanece en la vid, así tampoco vosotros, si no permanecéis en mí. Yo soy la vid, vosotros los pámpanos; el que permanece en mí, y yo en él, éste lleva mucho fruto; porque separados de mí nada podéis hacer.",
        "1 Corinthians 1:30-31": "Mas por él estáis vosotros en Cristo Jesús, el cual nos ha sido hecho por Dios sabiduría, justificación, santificación y redención; para que, como está escrito: El que se gloría, gloríese en el Señor.",
        "Colossians 2:10": "Y vosotros estáis completos en él, que es la cabeza de todo principado y potestad.",
        "John 14:6": "Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.",
        "Hebrews 7:25": "Por lo cual puede también salvar perpetuamente a los que por él se acercan a Dios, viviendo siempre para interceder por ellos.",
        "Acts 3:22": "Porque Moisés dijo a los padres: El Señor vuestro Dios os levantará profeta de entre vuestros hermanos, como a mí; a él oiréis en todas las cosas que os hable.",
        "Deuteronomy 18:15": "Profeta de en medio de ti, de tus hermanos, como yo, te levantará Jehová tu Dios; a él oiréis.",
        "Hebrews 4:14-15": "Por tanto, teniendo un gran sumo sacerdote que traspasó los cielos, Jesús el Hijo de Dios, retengamos nuestra profesión. Porque no tenemos un sumo sacerdote que no pueda compadecerse de nuestras debilidades, sino uno que fue tentado en todo según nuestra semejanza, pero sin pecado.",
        "Psalms 2:6": "Pero yo he puesto mi rey sobre Sion, mi santo monte.",
        "Luke 1:33": "Y reinará sobre la casa de Jacob para siempre, y su reino no tendrá fin.",
        "1 John 2:27": "Pero la unción que vosotros recibisteis de él permanece en vosotros, y no tenéis necesidad de que nadie os enseñe.",
        "Acts 11:26": "Y se congregaron allí todo un año con la iglesia, y enseñaron a mucha gente; y a los discípulos se les llamó cristianos por primera vez en Antioquía.",
        "Revelation 1:6": "Y nos hizo reyes y sacerdotes para Dios, su Padre; a él sea gloria e imperio por los siglos de los siglos. Amén.",
        "1 Peter 2:9": "Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios, para que anunciéis las virtudes de aquel que os llamó de las tinieblas a su luz admirable.",
        "Romans 12:1": "Así que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional.",
        "John 1:14": "Y aquel Verbo fue hecho carne, y habitó entre nosotros (y vimos su gloria, gloria como del unigénito del Padre), lleno de gracia y de verdad.",
        "John 1:18": "A Dios nadie le vio jamás; el unigénito Hijo, que está en el seno del Padre, él le ha dado a conocer.",
        "Romans 8:15-17": "Pues no habéis recibido el espíritu de esclavitud para estar otra vez en temor, sino que habéis recibido el espíritu de adopción, por el cual clamamos: ¡Abba, Padre! El Espíritu mismo da testimonio a nuestro espíritu, de que somos hijos de Dios. Y si hijos, también herederos; herederos de Dios y coherederos con Cristo.",
        "Galatians 4:4-7": "Pero cuando vino el cumplimiento del tiempo, Dios envió a su Hijo, nacido de mujer y nacido bajo la ley, para que redimiese a los que estaban bajo la ley, a fin de que recibiésemos la adopción de hijos. Y por cuanto sois hijos, Dios envió a vuestros corazones el Espíritu de su Hijo, el cual clama: ¡Abba, Padre! Así que ya no eres esclavo, sino hijo; y si hijo, también heredero de Dios por medio de Cristo.",
        "1 Peter 1:18-19": "Sabiendo que fuisteis rescatados de vuestra vana manera de vivir, no con cosas corruptibles, como oro o plata, sino con la sangre preciosa de Cristo, como de un cordero sin mancha y sin contaminación.",
        "1 Corinthians 6:20": "Porque habéis sido comprados por precio; glorificad, pues, a Dios en vuestro cuerpo y en vuestro espíritu, los cuales son de Dios.",
        "Colossians 1:13-14": "El cual nos ha librado de la potestad de las tinieblas, y trasladado al reino de su amado Hijo, en quien tenemos redención por su sangre, el perdón de pecados.",

        # === PREGUNTAS 35-52 (Sufrimiento, muerte, resurrección, ascensión) ===
        "Luke 1:35": "Respondiendo el ángel, le dijo: El Espíritu Santo vendrá sobre ti, y el poder del Altísimo te cubrirá con su sombra; por lo cual también el Santo Ser que nacerá, será llamado Hijo de Dios.",
        "Galatians 4:4": "Pero cuando vino el cumplimiento del tiempo, Dios envió a su Hijo, nacido de mujer y nacido bajo la ley.",
        "Hebrews 2:14": "Así que, por cuanto los hijos participaron de carne y sangre, él también participó de lo mismo, para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es, al diablo.",
        "Hebrews 4:15": "Porque no tenemos un sumo sacerdote que no pueda compadecerse de nuestras debilidades, sino uno que fue tentado en todo según nuestra semejanza, pero sin pecado.",
        "1 John 1:9": "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.",
        "Psalms 51:5": "He aquí, en maldad he sido formado, y en pecado me concibió mi madre.",
        "1 Peter 2:24": "Quien llevó él mismo nuestros pecados en su cuerpo sobre el madero, para que nosotros, estando muertos a los pecados, vivamos a la justicia; y por cuya herida fuisteis sanados.",
        "1 John 2:2": "Y él es la propiciación por nuestros pecados; y no solamente por los nuestros, sino también por los de todo el mundo.",
        "Luke 23:13-24": "Entonces Pilato, convocando a los principales sacerdotes, a los gobernantes, y al pueblo, les dijo: Me habéis presentado a éste como un hombre que perturba al pueblo; pero habiéndole interrogado yo delante de vosotros, no he hallado en este hombre delito alguno.",
        "Acts 4:27-28": "Porque verdaderamente se unieron en esta ciudad contra tu santo Hijo Jesús, a quien ungiste, Herodes y Poncio Pilato, con los gentiles y el pueblo de Israel, para hacer cuanto tu mano y tu consejo habían antes determinado que sucediera.",
        "John 19:13-16": "Entonces Pilato, oyendo esto, llevó fuera a Jesús, y se sentó en el tribunal en el lugar llamado el Enlosado, y en hebreo Gabata.",
        "Galatians 3:13": "Cristo nos redimió de la maldición de la ley, hecho por nosotros maldición (porque está escrito: Maldito todo el que es colgado en un madero).",
        "Deuteronomy 21:23": "No dejaréis que su cuerpo pase la noche sobre el madero; sin falta lo enterrarás el mismo día, porque maldito por Dios es el colgado.",
        "Philippians 2:8": "Y estando en la condición de hombre, se humilló a sí mismo, haciéndose obediente hasta la muerte, y muerte de cruz.",
        "Romans 6:23": "Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro.",
        "Hebrews 2:9": "Pero vemos a aquel que fue hecho un poco menor que los ángeles, a Jesús, coronado de gloria y de honra, a causa del padecimiento de la muerte.",
        "Hebrews 9:22": "Y casi todo es purificado, según la ley, con sangre; y sin derramamiento de sangre no se hace remisión.",
        "John 19:38-42": "Después de todo esto, José de Arimatea, que era discípulo de Jesús, pero secretamente por miedo de los judíos, rogó a Pilato que le permitiese llevarse el cuerpo de Jesús; y Pilato se lo concedió.",
        "Acts 13:29": "Y habiendo cumplido todas las cosas que de él estaban escritas, quitándolo del madero, lo pusieron en el sepulcro.",
        "Philippians 1:21-23": "Porque para mí el vivir es Cristo, y el morir es ganancia. Teniendo deseo de partir y estar con Cristo, lo cual es muchísimo mejor.",
        "John 5:24": "De cierto, de cierto os digo: El que oye mi palabra, y cree al que me envió, tiene vida eterna; y no vendrá a condenación, mas ha pasado de muerte a vida.",
        "Romans 7:24-25": "¡Miserable de mí! ¿quién me librará de este cuerpo de muerte? Gracias doy a Dios, por Jesucristo Señor nuestro.",
        "Romans 6:5-11": "Porque si fuimos plantados juntamente con él en la semejanza de su muerte, así también lo seremos en la de su resurrección; sabiendo esto, que nuestro viejo hombre fue crucificado juntamente con él, para que el cuerpo del pecado sea destruido, a fin de que no sirvamos más al pecado.",
        "Colossians 3:5": "Haced morir, pues, lo terrenal en vosotros: fornicación, impureza, pasiones desordenadas, malos deseos y avaricia, que es idolatría.",
        "Matthew 27:46": "Cerca de la hora novena, Jesús clamó a gran voz, diciendo: Elí, Elí, ¿lama sabactani? Esto es: Dios mío, Dios mío, ¿por qué me has desamparado?",
        "Isaiah 53:10": "Con todo eso, Jehová quiso quebrantarlo, sujetándole a padecimiento.",
        "Psalms 18:5-6": "Ligaduras del Seol me rodearon, me tendieron lazos de muerte. En mi angustia invoqué a Jehová, y clamé a mi Dios. El oyó mi voz desde su templo, y mi clamor llegó delante de él, a sus oídos.",
        "Psalms 116:3": "Me rodearon ligaduras de muerte, me encontraron las angustias del Seol; angustia y dolor había yo hallado.",
        "Romans 4:25": "El cual fue entregado por nuestras transgresiones, y resucitado para nuestra justificación.",
        "1 Corinthians 15:17-20": "Y si Cristo no resucitó, vuestra fe es vana; aún estáis en vuestros pecados. Mas ahora Cristo ha resucitado de los muertos; primicias de los que durmieron es hecho.",
        "Romans 6:4": "Porque somos sepultados juntamente con él para muerte por el bautismo, a fin de que como Cristo resucitó de los muertos por la gloria del Padre, así también nosotros andemos en vida nueva.",
        "Ephesians 2:4-6": "Pero Dios, que es rico en misericordia, por su gran amor con que nos amó, aun estando nosotros muertos en pecados, nos dio vida juntamente con Cristo, y juntamente con él nos resucitó, y asimismo nos hizo sentar en los lugares celestiales con Cristo Jesús.",
        "Philippians 3:20-21": "Mas nuestra ciudadanía está en los cielos, de donde también esperamos al Salvador, al Señor Jesucristo; el cual transformará el cuerpo de la humillación nuestra, para que sea semejante al cuerpo de la gloria suya.",
        "Acts 1:9-11": "Y habiendo dicho estas cosas, viéndolo ellos, fue alzado, y le recibió una nube que le ocultó de sus ojos. Y estando ellos con los ojos puestos en el cielo, entre tanto que él se iba, he aquí se pusieron junto a ellos dos varones con vestiduras blancas, los cuales también les dijeron: Varones galileos, ¿por qué estáis mirando al cielo? Este mismo Jesús, que ha sido tomado de vosotros al cielo, así vendrá como le habéis visto ir al cielo.",
        "Mark 16:19": "Y el Señor, después que les habló, fue recibido arriba en el cielo, y se sentó a la diestra de Dios.",
        "Hebrews 4:14": "Por tanto, teniendo un gran sumo sacerdote que traspasó los cielos, Jesús el Hijo de Dios, retengamos nuestra profesión.",
        "Hebrews 9:24": "Porque no entró Cristo en el santuario hecho de mano, figura del verdadero, sino en el cielo mismo para presentarse ahora por nosotros ante Dios.",
        "Matthew 28:20": "Enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.",
        "John 14:16-18": "Y yo rogaré al Padre, y os dará otro Consolador, para que esté con vosotros para siempre: el Espíritu de verdad. No os dejaré huérfanos; vendré a vosotros.",
        "Matthew 18:20": "Porque donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.",
        "Acts 1:11": "Los cuales también les dijeron: Varones galileos, ¿por qué estáis mirando al cielo? Este mismo Jesús, que ha sido tomado de vosotros al cielo, así vendrá como le habéis visto ir al cielo.",
        "Acts 3:21": "A quien de cierto es necesario que el cielo reciba hasta los tiempos de la restauración de todas las cosas.",
        "John 17:11": "Y ya no estoy en el mundo; mas éstos están en el mundo, y yo voy a ti. Padre santo, a los que me has dado, guárdalos en tu nombre, para que sean uno, así como nosotros.",
        "Colossians 2:9": "Porque en él habita corporalmente toda la plenitud de la Deidad.",
        "Romans 8:34": "¿Quién es el que condenará? Cristo es el que murió; más aun, el que también resucitó, el que además está a la diestra de Dios, el que también intercede por nosotros.",
        "1 John 2:1": "Hijitos míos, estas cosas os escribo para que no pequéis; y si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo.",
        "John 14:2": "En la casa de mi Padre muchas moradas hay; si así no fuera, yo os lo hubiera dicho; voy, pues, a preparar lugar para vosotros.",
        "John 16:7": "Pero yo os digo la verdad: Os conviene que yo me vaya; porque si no me fuera, el Consolador no vendría a vosotros; mas si me fuere, os lo enviaré.",
        "Colossians 3:1-2": "Si, pues, habéis resucitado con Cristo, buscad las cosas de arriba, donde está Cristo sentado a la diestra de Dios. Poned la mira en las cosas de arriba, no en las de la tierra.",
        "Ephesians 1:20-23": "La cual operó en Cristo, resucitándole de los muertos y sentándole a su diestra en los lugares celestiales, sobre todo principado y autoridad y poder y señorío, y sobre todo nombre que se nombra, no sólo en este siglo, sino también en el venidero; y sometió todas las cosas bajo sus pies, y lo dio por cabeza sobre todas las cosas a la iglesia.",
        "Colossians 1:18": "Y él es la cabeza del cuerpo que es la iglesia, él que es el principio, el primogénito de entre los muertos, para que en todo tenga la preeminencia.",
        "Matthew 28:18": "Y Jesús se acercó y les habló diciendo: Toda potestad me es dada en el cielo y en la tierra.",
        "Acts 2:33": "Así que, exaltado por la diestra de Dios, y habiendo recibido del Padre la promesa del Espíritu Santo, ha derramado esto que vosotros veis y oís.",
        "Ephesians 4:8-12": "Por lo cual dice: Subiendo a lo alto, llevó cautiva la cautividad, y dio dones a los hombres. Y él mismo constituyó a unos, apóstoles; a otros, profetas; a otros, evangelistas; a otros, pastores y maestros.",
        "Psalms 2:9": "Los quebrantarás con vara de hierro; como vasija de alfarero los desmenuzarás.",
        "Matthew 25:31-34": "Cuando el Hijo del Hombre venga en su gloria, y todos los santos ángeles con él, entonces se sentará en su trono de gloria. Entonces el Rey dirá a los de su derecha: Venid, benditos de mi Padre, heredad el reino preparado para vosotros desde la fundación del mundo.",
        "Philippians 3:20": "Mas nuestra ciudadanía está en los cielos, de donde también esperamos al Salvador, al Señor Jesucristo.",
        "Luke 21:28": "Cuando estas cosas comiencen a suceder, erguíos y levantad vuestra cabeza, porque vuestra redención está cerca.",
        "Titus 2:13": "Aguardando la esperanza bienaventurada y la manifestación gloriosa de nuestro gran Dios y Salvador Jesucristo.",
        "2 Thessalonians 1:6-10": "Porque es justo delante de Dios pagar con tribulación a los que os atribulan, y a vosotros que sois atribulados, daros reposo con nosotros, cuando se manifieste el Señor Jesús desde el cielo con los ángeles de su poder.",

        # === PREGUNTAS 53-58 (Espíritu Santo, Iglesia, Vida eterna) ===
        "1 Peter 1:2": "Elegidos según la satisfacción de Dios Padre en santificación del Espíritu, para obedecer y ser rociados con la sangre de Jesucristo.",
        "Galatians 4:6": "Y por cuanto sois hijos, Dios envió a vuestros corazones el Espíritu de su Hijo, el cual clama: ¡Abba, Padre!",
        "Romans 8:16": "El Espíritu mismo da testimonio a nuestro espíritu, de que somos hijos de Dios.",
        "John 15:26": "Pero cuando venga el Consolador, a quien yo os enviaré del Padre, el Espíritu de verdad, el cual procede del Padre, él dará testimonio acerca de mí.",
        "John 10:27-29": "Mis ovejas oyen mi voz, y yo las conozco, y me siguen, y yo les doy vida eterna; y no perecerán jamás, ni nadie las arrebatará de mi mano. Mi Padre que me las dio, es mayor que todos, y nadie las puede arrebatar de la mano de mi Padre.",
        "Ephesians 1:10-13": "En él asimismo tuvimos herencia, habiendo sido predestinados conforme al propósito del que hace todas las cosas según el designio de su voluntad. En él también vosotros, habiendo oído la palabra de verdad, el evangelio de vuestra salvación, y habiendo creído en él, fuisteis sellados con el Espíritu Santo de la promesa.",
        "Acts 2:46-47": "Y perseverando unánimes cada día en el templo, y partiendo el pan en las casas, comían juntos con alegría y sencillez de corazón, alabando a Dios, y teniendo favor con todo el pueblo. Y el Señor añadía cada día a la iglesia los que habían de ser salvos.",
        "Isaiah 59:21": "Y este será mi pacto con ellos, dijo Jehová: El Espíritu mío que está sobre ti, y mis palabras que puse en tu boca, no faltarán de tu boca.",
        "1 John 3:21": "Amados, si nuestro corazón no nos reprende, confianza tenemos en Dios.",
        "1 Corinthians 12:12-13": "Porque así como el cuerpo es uno, y tiene muchos miembros, pero todos los miembros del cuerpo, siendo muchos, son un solo cuerpo, así también Cristo. Porque por un solo Espíritu fuimos todos bautizados en un cuerpo.",
        "1 Corinthians 12:21": "Ni el ojo puede decir a la mano: No te necesito, ni tampoco la cabeza a los pies: No tengo necesidad de vosotros.",
        "Romans 12:4-5": "Porque de la manera que en un cuerpo tenemos muchos miembros, pero no todos los miembros tienen la misma función, así nosotros, siendo muchos, somos un cuerpo en Cristo, y todos miembros los unos de los otros.",
        "1 John 1:3": "Lo que hemos visto y oído, eso os anunciamos, para que también vosotros tengáis comunión con nosotros; y nuestra comunión verdaderamente es con el Padre, y con su Hijo Jesucristo.",
        "Romans 4:6-8": "Como también David habla de la bienaventuranza del hombre a quien Dios atribuye justicia sin obras, diciendo: Bienaventurados aquellos cuyas iniquidades son perdonadas, y cuyos pecados son cubiertos. Bienaventurado el varón a quien el Señor no inculpa de pecado.",
        "2 Corinthians 5:19-21": "Que Dios estaba en Cristo reconciliando consigo al mundo, no tomándoles en cuenta a los hombres sus pecados. Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él.",
        "Jeremiah 31:34": "Y no enseñará más ninguno a su prójimo, ni ninguno a su hermano, diciendo: Conoce a Jehová; porque todos me conocerán, desde el más pequeño de ellos hasta el más grande, dice Jehová; porque perdonaré la maldad de ellos, y no me acordaré más de su pecado.",
        "Micah 7:19": "Él volverá a tener misericordia de nosotros; sepultará nuestras iniquidades, y echará en lo profundo del mar todos nuestros pecados.",
        "John 6:39-40": "Y esta es la voluntad del Padre, el que me envió: Que de todo lo que me diere, no pierda yo nada, sino que lo resucite en el día postrero. Y esta es la voluntad del que me ha enviado: Que todo aquel que ve al Hijo, y cree en él, tenga vida eterna; y yo le resucitaré en el día postrero.",
        "1 Corinthians 15:42-44": "Así también es la resurrección de los muertos. Se siembra en corrupción, resucitará en incorrupción. Se siembra en deshonra, resucitará en gloria; se siembra en debilidad, resucitará en poder. Se siembra cuerpo animal, resucitará cuerpo espiritual.",
        "Job 19:25-26": "Yo sé que mi Redentor vive, y al fin se levantará sobre el polvo; y después de deshecha esta mi piel, en mi carne he de ver a Dios.",
        "2 Corinthians 5:1-5": "Porque sabemos que si nuestra morada terrestre, este tabernáculo, se deshiciere, tenemos de Dios un edificio, una casa no hecha de manos, eterna, en los cielos.",
        "Romans 8:23": "Y no sólo ella, sino que también nosotros mismos, que tenemos las primicias del Espíritu, nosotros también gemimos dentro de nosotros mismos, esperando la adopción, la redención de nuestro cuerpo.",
        "1 Corinthians 2:9": "Antes bien, como está escrito: Cosas que ojo no vio, ni oído oyó, ni han subido en corazón de hombre, son las que Dios ha preparado para los que le aman.",
        "John 17:3": "Y esta es la vida eterna: que te conozcan a ti, el único Dios verdadero, y a Jesucristo, a quien has enviado.",

        # === PREGUNTAS 59-67 (Justificación y Sacramentos) ===
        "Romans 1:17": "Porque en el evangelio la justicia de Dios se revela por fe y para fe, como está escrito: Mas el justo por la fe vivirá.",
        "Habakkuk 2:4": "He aquí que aquel cuya alma no es recta, se enorgullece; mas el justo por su fe vivirá.",
        "Romans 5:1": "Justificados, pues, por la fe, tenemos paz para con Dios por medio de nuestro Señor Jesucristo.",
        "John 3:36": "El que cree en el Hijo tiene vida eterna; pero el que rehúsa creer en el Hijo no verá la vida, sino que la ira de Dios está sobre él.",
        "Romans 3:21-26": "Pero ahora, aparte de la ley, se ha manifestado la justicia de Dios, testificada por la ley y por los profetas; la justicia de Dios por medio de la fe en Jesucristo, para todos los que creen en él. Porque no hay diferencia, por cuanto todos pecaron, y están destituidos de la gloria de Dios, siendo justificados gratuitamente por su gracia, mediante la redención que es en Cristo Jesús.",
        "Romans 4:4-5": "Pero al que obra, no se le cuenta el salario como gracia, sino como deuda; mas al que no obra, sino cree en aquel que justifica al impío, su fe le es contada por justicia.",
        "2 Corinthians 5:21": "Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él.",
        "Galatians 2:16": "Sabiendo que el hombre no es justificado por las obras de la ley, sino por la fe de Jesucristo.",
        "Romans 3:28": "Concluimos, pues, que el hombre es justificado por fe sin las obras de la ley.",
        "Galatians 3:11": "Y que por la ley ninguno se justifica para con Dios, es evidente, porque: El justo por la fe vivirá.",
        "Romans 10:10": "Porque con el corazón se cree para justicia, pero con la boca se confiesa para salvación.",
        "Philippians 3:8-9": "Y ciertamente, aun estimo todas las cosas como pérdida por la excelencia del conocimiento de Cristo Jesús, mi Señor, por amor del cual lo he perdido todo, y lo tengo por basura, para ganar a Cristo, y ser hallado en él, no teniendo mi propia justicia, que es por la ley, sino la que es por la fe de Cristo, la justicia que es de Dios por la fe.",
        "Romans 4:4": "Pero al que obra, no se le cuenta el salario como gracia, sino como deuda.",
        "Luke 17:10": "Así también vosotros, cuando hayáis hecho todo lo que os ha sido ordenado, decid: Siervos inútiles somos, pues lo que debíamos hacer, hicimos.",
        "Matthew 5:12": "Gozaos y alegraos, porque vuestro galardón es grande en los cielos.",
        "Hebrews 11:6": "Pero sin fe es imposible agradar a Dios; porque es necesario que el que se acerca a Dios crea que le hay, y que es galardonador de los que le buscan.",
        "Matthew 7:17-18": "Así, todo buen árbol da buenos frutos, pero el árbol malo da frutos malos. No puede el buen árbol dar malos frutos, ni el árbol malo dar frutos buenos.",
        "Galatians 5:22-24": "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza; contra tales cosas no hay ley. Pero los que son de Cristo han crucificado la carne con sus pasiones y deseos.",
        "John 15:5": "Yo soy la vid, vosotros los pámpanos; el que permanece en mí, y yo en él, éste lleva mucho fruto; porque separados de mí nada podéis hacer.",
        "Romans 6:1-2": "¿Qué, pues, diremos? ¿Perseveraremos en el pecado para que la gracia abunde? En ninguna manera. Porque los que hemos muerto al pecado, ¿cómo viviremos aún en él?",
        "Ephesians 2:8": "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.",
        "Philippians 1:29": "Porque a vosotros os es concedido a causa de Cristo, no sólo que creáis en él, sino también que padezcáis por él.",
        "Romans 10:17": "Así que la fe es por el oír, y el oír, por la palabra de Dios.",
        "Acts 16:14": "Entonces una mujer llamada Lidia, vendedora de púrpura, de la ciudad de Tiatira, que adoraba a Dios, estaba oyendo; y el Señor abrió el corazón de ella para que estuviese atenta a lo que Pablo decía.",
        "1 Peter 1:23-25": "Siendo renacidos, no de simiente corruptible, sino de incorruptible, por la palabra de Dios que vive y permanece para siempre.",
        "Genesis 17:7": "Y estableceré mi pacto entre mí y ti, y tu descendencia después de ti en sus generaciones, por pacto perpetuo, para ser tu Dios, y el de tu descendencia después de ti.",
        "Romans 4:11": "Y recibió la circuncisión como señal, como sello de la justicia de la fe que tuvo estando aún incircunciso.",
        "Deuteronomy 30:6": "Y circuncidará Jehová tu Dios tu corazón, y el corazón de tu descendencia, para que ames a Jehová tu Dios con todo tu corazón y con toda tu alma, a fin de que vivas.",
        "Acts 2:38": "Pedro les dijo: Arrepentíos, y bautícese cada uno de vosotros en el nombre de Jesucristo para perdón de los pecados; y recibiréis el don del Espíritu Santo.",
        "Hebrews 9:12-14": "Y no por sangre de machos cabríos ni de becerros, sino por su propia sangre, entró una vez para siempre en el Lugar Santísimo, habiendo obtenido eterna redención.",

        # === PREGUNTAS 68-82 (Bautismo y Santa Cena) ===
        "1 Corinthians 11:23-26": "Porque yo recibí del Señor lo que también os he enseñado: Que el Señor Jesús, la noche que fue entregado, tomó pan; y habiendo dado gracias, lo partió, y dijo: Tomad, comed; esto es mi cuerpo que por vosotros es partido; haced esto en memoria de mí. Asimismo tomó también la copa, después de haber cenado, diciendo: Esta copa es el nuevo pacto en mi sangre; haced esto todas las veces que la bebiereis, en memoria de mí. Así, pues, todas las veces que comiereis este pan, y bebiereis esta copa, la muerte del Señor anunciáis hasta que él venga.",
        "Matthew 26:26-28": "Y mientras comían, tomó Jesús el pan, y bendijo, y lo partió, y dio a sus discípulos, y dijo: Tomad, comed; esto es mi cuerpo. Y tomando la copa, y habiendo dado gracias, les dio, diciendo: Bebed de ella todos; porque esto es mi sangre del nuevo pacto, que por muchos es derramada para remisión de los pecados.",
        "Matthew 26:28": "Porque esto es mi sangre del nuevo pacto, que por muchos es derramada para remisión de los pecados.",
        "Mark 14:24": "Y les dijo: Esto es mi sangre del nuevo pacto, que por muchos es derramada.",
        "Hebrews 10:10": "En esa voluntad somos santificados mediante la ofrenda del cuerpo de Jesucristo hecha una vez para siempre.",
        "1 John 1:7": "Pero si andamos en luz, como él está en luz, tenemos comunión unos con otros, y la sangre de Jesucristo su Hijo nos limpia de todo pecado.",
        "Revelation 1:5": "Y de Jesucristo el testigo fiel, el primogénito de los muertos, y el soberano de los reyes de la tierra. Al que nos amó, y nos lavó de nuestros pecados con su sangre.",
        "John 3:5": "Respondió Jesús: De cierto, de cierto te digo, que el que no naciere de agua y del Espíritu, no puede entrar en el reino de Dios.",
        "Mark 16:16": "El que creyere y fuere bautizado, será salvo; mas el que no creyere, será condenado.",
        "Titus 3:5": "Nos salvó, no por obras de justicia que nosotros hubiéramos hecho, sino por su misericordia, por el lavamiento de la regeneración y por la renovación en el Espíritu Santo.",
        "Acts 22:16": "Ahora, pues, ¿por qué te detienes? Levántate y bautízate, y lava tus pecados, invocando su nombre.",
        "Romans 6:3-4": "¿O no sabéis que todos los que hemos sido bautizados en Cristo Jesús, hemos sido bautizados en su muerte? Porque somos sepultados juntamente con él para muerte por el bautismo.",
        "Galatians 3:27": "Porque todos los que habéis sido bautizados en Cristo, de Cristo estáis revestidos.",
        "1 Peter 3:21": "El bautismo que corresponde a esto ahora nos salva (no quitando las inmundicias de la carne, sino como la aspiración de una buena conciencia hacia Dios) por la resurrección de Jesucristo.",
        "Ephesians 5:26": "Para santificarla, habiéndola purificado en el lavamiento del agua por la palabra.",
        "Matthew 19:14": "Pero Jesús dijo: Dejad a los niños venir a mí, y no se lo impidáis; porque de los tales es el reino de los cielos.",
        "Acts 2:38-39": "Pedro les dijo: Arrepentíos, y bautícese cada uno de vosotros en el nombre de Jesucristo para perdón de los pecados; y recibiréis el don del Espíritu Santo. Porque para vosotros es la promesa, y para vuestros hijos, y para todos los que están lejos; para cuantos el Señor nuestro Dios llamare.",
        "Colossians 2:11-12": "En él también fuisteis circuncidados con circuncisión no hecha a mano, al echar de vosotros el cuerpo pecaminoso carnal, en la circuncisión de Cristo; sepultados con él en el bautismo.",
        "1 Corinthians 7:14": "Porque el marido incrédulo es santificado en la mujer, y la mujer incrédula en el marido; pues de otra manera vuestros hijos serían inmundos, mientras que ahora son santos.",
        "Luke 22:19-20": "Y tomó el pan y dio gracias, y lo partió y les dio, diciendo: Esto es mi cuerpo, que por vosotros es dado; haced esto en memoria de mí. De igual manera, después que hubo cenado, tomó la copa, diciendo: Esta copa es el nuevo pacto en mi sangre, que por vosotros se derrama.",
        "John 6:51": "Yo soy el pan vivo que descendió del cielo; si alguno comiere de este pan, vivirá para siempre; y el pan que yo daré es mi carne, la cual yo daré por la vida del mundo.",
        "John 6:55-56": "Porque mi carne es verdadera comida, y mi sangre es verdadera bebida. El que come mi carne y bebe mi sangre, permanece en mí, y yo en él.",
        "1 Corinthians 10:16-17": "La copa de bendición que bendecimos, ¿no es la comunión de la sangre de Cristo? El pan que partimos, ¿no es la comunión del cuerpo de Cristo? Siendo uno solo el pan, nosotros, con ser muchos, somos un cuerpo; pues todos participamos de aquel mismo pan.",
        "Ephesians 5:30": "Porque somos miembros de su cuerpo, de su carne y de sus huesos.",
        "John 6:55-58": "Porque mi carne es verdadera comida, y mi sangre es verdadera bebida. El que come mi carne y bebe mi sangre, permanece en mí, y yo en él. Como me envió el Padre viviente, y yo vivo por el Padre, asimismo el que me come, él también vivirá por mí.",
        "Mark 14:22-24": "Y mientras comían, Jesús tomó pan y bendijo, y lo partió y les dio, diciendo: Tomad, esto es mi cuerpo. Y tomando la copa, y habiendo dado gracias, les dio; y bebieron de ella todos. Y les dijo: Esto es mi sangre del nuevo pacto, que por muchos es derramada.",
        "1 Corinthians 10:1-4": "Porque no quiero, hermanos, que ignoréis que nuestros padres todos estuvieron bajo la nube, y todos pasaron el mar; y todos comieron el mismo alimento espiritual, y todos bebieron la misma bebida espiritual; porque bebían de la roca espiritual que los seguía, y la roca era Cristo.",
        "1 Corinthians 11:26": "Así, pues, todas las veces que comiereis este pan, y bebiereis esta copa, la muerte del Señor anunciáis hasta que él venga.",
        "1 Corinthians 11:26-28": "Así, pues, todas las veces que comiereis este pan, y bebiereis esta copa, la muerte del Señor anunciáis hasta que él venga. De manera que cualquiera que comiere este pan o bebiere esta copa del Señor indignamente, será culpado del cuerpo y de la sangre del Señor. Por tanto, pruébese cada uno a sí mismo, y coma así del pan, y beba de la copa.",
        "Hebrews 10:10-14": "En esa voluntad somos santificados mediante la ofrenda del cuerpo de Jesucristo hecha una vez para siempre. Porque con una sola ofrenda hizo perfectos para siempre a los santificados.",
        "Hebrews 10:18": "Pues donde hay remisión de éstos, no hay más ofrenda por el pecado.",
        "Hebrews 7:26-27": "Porque tal sumo sacerdote nos convenía: santo, inocente, sin mancha, apartado de los pecadores, y hecho más sublime que los cielos; que no tiene necesidad cada día, como aquellos sumos sacerdotes, de ofrecer primero sacrificios por sus propios pecados, y luego por los del pueblo; porque esto lo hizo una vez para siempre, ofreciéndose a sí mismo.",
        "Hebrews 9:12": "Y no por sangre de machos cabríos ni de becerros, sino por su propia sangre, entró una vez para siempre en el Lugar Santísimo, habiendo obtenido eterna redención.",
        "John 19:30": "Cuando Jesús hubo tomado el vinagre, dijo: Consumado es. Y habiendo inclinado la cabeza, entregó el espíritu.",
        "1 Corinthians 11:28-29": "Por tanto, pruébese cada uno a sí mismo, y coma así del pan, y beba de la copa. Porque el que come y bebe indignamente, sin discernir el cuerpo del Señor, juicio come y bebe para sí.",
        "1 Corinthians 10:19-22": "¿Qué digo, pues? ¿Que el ídolo es algo, o que sea algo lo que se sacrifica a los ídolos? Antes digo que lo que los gentiles sacrifican, a los demonios lo sacrifican, y no a Dios; y no quiero que vosotros os hagáis partícipes con los demonios.",
        "Psalms 50:15-16": "E invócame en el día de la angustia; te libraré, y tú me honrarás. Pero al malo dijo Dios: ¿Qué tienes tú que hablar de mis leyes?",
        "1 Corinthians 11:20-32": "Cuando, pues, os reunís vosotros, esto no es comer la cena del Señor. Porque al comer, cada uno se adelanta a tomar su propia cena; y uno tiene hambre, y otro se embriaga.",
        "Matthew 18:17": "Si no los oyere a ellos, dilo a la iglesia; y si no oyere a la iglesia, tenle por gentil y publicano.",
        "Isaiah 1:11-17": "¿Para qué me sirve, dice Jehová, la multitud de vuestros sacrificios? Laveos y limpiaos; quitad la iniquidad de vuestras obras de delante de mis ojos; dejad de hacer lo malo; aprended a hacer el bien.",

        # === PREGUNTAS 83-85 (Llaves del Reino) ===
        "Matthew 16:19": "Y a ti te daré las llaves del reino de los cielos; y todo lo que atares en la tierra será atado en los cielos; y todo lo que desatares en la tierra será desatado en los cielos.",
        "Matthew 18:18": "De cierto os digo que todo lo que atéis en la tierra, será atado en el cielo; y todo lo que desatéis en la tierra, será desatado en el cielo.",
        "John 20:22-23": "Y habiendo dicho esto, sopló, y les dijo: Recibid el Espíritu Santo. A quienes remitiereis los pecados, les son remitidos; y a quienes se los retuviereis, les son retenidos.",
        "John 20:21-23": "Entonces Jesús les dijo otra vez: Paz a vosotros. Como me envió el Padre, así también yo os envío. Y habiendo dicho esto, sopló, y les dijo: Recibid el Espíritu Santo. A quienes remitiereis los pecados, les son remitidos; y a quienes se los retuviereis, les son retenidos.",
        "2 Corinthians 2:15-16": "Porque para Dios somos grato olor de Cristo en los que se salvan, y en los que se pierden; a éstos ciertamente olor de muerte para muerte, y a aquéllos olor de vida para vida.",
        "Matthew 18:15-18": "Por tanto, si tu hermano peca contra ti, ve y repréndele estando tú y él solos; si te oyere, has ganado a tu hermano.",
        "1 Corinthians 5:3-5": "Ciertamente yo, como ausente en cuerpo, pero presente en espíritu, ya como presente he juzgado al que tal cosa ha hecho.",
        "2 Corinthians 2:6-8": "Le basta a tal persona esta reprensión hecha por muchos; así que, al contrario, vosotros más bien debéis perdonarle y consolarle, para que no sea consumido de demasiada tristeza. Por lo cual os ruego que confirméis el amor para con él.",
        "2 Thessalonians 3:14-15": "Si alguno no obedece a lo que decimos por medio de esta carta, a ése señaladlo, y no os juntéis con él, para que se avergüence. Mas no lo tengáis por enemigo, sino amonestadle como a hermano.",

        # === PREGUNTAS 86-115 (Gratitud, Mandamientos, Ley) ===
        "Romans 6:13": "Ni tampoco presentéis vuestros miembros al pecado como instrumentos de iniquidad, sino presentaos vosotros mismos a Dios como vivos de entre los muertos.",
        "Romans 12:1-2": "Así que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional. No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento.",
        "1 Peter 2:9-10": "Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios.",
        "Matthew 5:16": "Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos.",
        "1 Peter 2:12": "Manteniendo buena vuestra manera de vivir entre los gentiles; para que en lo que murmuran de vosotros como de malhechores, glorifiquen a Dios en el día de la visitación, al considerar vuestras buenas obras.",
        "1 Corinthians 6:9-10": "¿No sabéis que los injustos no heredarán el reino de Dios? No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados, ni los que se echan con varones, ni los ladrones, ni los avaros, ni los borrachos, ni los maldicientes, ni los estafadores, heredarán el reino de Dios.",
        "Galatians 5:19-21": "Y manifiestas son las obras de la carne, que son: adulterio, fornicación, inmundicia, lascivia, idolatría, hechicerías, enemistades, pleitos, celos, iras, contiendas, disensiones, herejías, envidias, homicidios, borracheras, orgías, y cosas semejantes a estas.",
        "Ephesians 5:5-6": "Porque sabéis esto, que ningún fornicario, o inmundo, o avaro, que es idólatra, tiene herencia en el reino de Cristo y de Dios. Nadie os engañe con palabras vanas.",
        "Romans 6:1-11": "¿Qué, pues, diremos? ¿Perseveraremos en el pecado para que la gracia abunde? En ninguna manera. Sabiendo esto, que nuestro viejo hombre fue crucificado juntamente con él.",
        "Colossians 3:5-10": "Haced morir, pues, lo terrenal en vosotros: fornicación, impureza, pasiones desordenadas, malos deseos y avaricia. Vestíos del nuevo hombre.",
        "Ephesians 4:22-24": "En cuanto a la pasada manera de vivir, despojaos del viejo hombre, que está viciado conforme a los deseos engañosos, y renovaos en el espíritu de vuestra mente, y vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad.",
        "Romans 8:13": "Porque si vivís conforme a la carne, moriréis; mas si por el Espíritu hacéis morir las obras de la carne, viviréis.",
        "Joel 2:13": "Rasgad vuestro corazón, y no vuestros vestidos, y convertíos a Jehová vuestro Dios; porque misericordioso es y clemente, tardo para la ira y grande en misericordia.",
        "2 Corinthians 7:10": "Porque la tristeza que es según Dios produce arrepentimiento para salvación, de que no hay que arrepentirse; pero la tristeza del mundo produce muerte.",
        "Romans 6:11": "Así también vosotros consideraos muertos al pecado, pero vivos para Dios en Cristo Jesús, Señor nuestro.",
        "Romans 14:17": "Porque el reino de Dios no es comida ni bebida, sino justicia, paz y gozo en el Espíritu Santo.",
        "Colossians 3:12-17": "Vestíos, pues, como escogidos de Dios, santos y amados, de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia. Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.",
        "Romans 12:2": "No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta.",
        "1 Samuel 15:22": "Y Samuel dijo: ¿Se complace Jehová tanto en los holocaustos y víctimas, como en que se obedezca a las palabras de Jehová? Ciertamente el obedecer es mejor que los sacrificios.",
        "Ephesians 2:10": "Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviésemos en ellas.",
        "Deuteronomy 12:32": "Cuidarás de hacer todo lo que yo te mando; no añadirás a ello, ni de ello quitarás.",
        "Exodus 20:1-17": "Y habló Dios todas estas palabras, diciendo: Yo soy Jehová tu Dios, que te saqué de la tierra de Egipto, de casa de servidumbre. No tendrás dioses ajenos delante de mí.",
        "Deuteronomy 5:6-21": "Yo soy Jehová tu Dios, que te saqué de tierra de Egipto, de casa de servidumbre. No tendrás dioses ajenos delante de mí.",
        "Deuteronomy 6:4-5": "Oye, Israel: Jehová nuestro Dios, Jehová uno es. Y amarás a Jehová tu Dios de todo tu corazón, y de toda tu alma, y con todas tus fuerzas.",
        "Matthew 4:10": "Entonces Jesús le dijo: Vete, Satanás, porque escrito está: Al Señor tu Dios adorarás, y a él sólo servirás.",
        "1 John 5:21": "Hijitos, guardaos de los ídolos. Amén.",
        "1 Corinthians 10:14": "Por tanto, amados míos, huid de la idolatría.",
        "Philippians 3:19": "El fin de los cuales será perdición, cuyo dios es el vientre, y cuya gloria es su vergüenza; que sólo piensan en lo terrenal.",
        "Ephesians 5:5": "Porque sabéis esto, que ningún fornicario, o inmundo, o avaro, que es idólatra, tiene herencia en el reino de Cristo y de Dios.",
        "Galatians 4:8": "Ciertamente, en otro tiempo, no conociendo a Dios, servíais a los que por naturaleza no son dioses.",
        "1 Chronicles 16:26": "Porque todos los dioses de los pueblos son ídolos; pero Jehová hizo los cielos.",

        # Mandamientos continuación
        "Deuteronomy 4:15-19": "Guardad, pues, mucho vuestras almas; pues ninguna figura visteis el día que Jehová habló con vosotros de en medio del fuego.",
        "Isaiah 40:18-25": "¿A qué, pues, haréis semejante a Dios, o qué imagen le compondréis?",
        "Acts 17:29": "Siendo, pues, linaje de Dios, no debemos pensar que la Divinidad sea semejante a oro, o plata, o piedra, escultura de arte y de imaginación de hombres.",
        "Romans 1:23": "Y cambiaron la gloria del Dios incorruptible en semejanza de imagen de hombre corruptible, de aves, de cuadrúpedos y de reptiles.",
        "John 4:24": "Dios es Espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren.",
        "2 Peter 1:19": "Tenemos también la palabra profética más segura, a la cual hacéis bien en estar atentos como a una antorcha que alumbra en lugar oscuro.",
        "2 Timothy 3:16-17": "Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia, a fin de que el hombre de Dios sea perfecto, enteramente preparado para toda buena obra.",
        "Exodus 20:7": "No tomarás el nombre de Jehová tu Dios en vano; porque no dará por inocente Jehová al que tomare su nombre en vano.",
        "Leviticus 24:15-16": "Y a los hijos de Israel hablarás, diciendo: Cualquiera que maldijere a su Dios, llevará su pecado. Y el que blasfemare el nombre de Jehová, ha de ser muerto.",
        "Matthew 5:34-37": "Pero yo os digo: No juréis en ninguna manera. Pero sea vuestro hablar: Sí, sí; no, no; porque lo que es más de esto, de mal procede.",
        "James 5:12": "Pero sobre todo, hermanos míos, no juréis, ni por el cielo, ni por la tierra, ni por ningún otro juramento; sino que vuestro sí sea sí, y vuestro no sea no, para que no caigáis en condenación.",
        "Leviticus 5:1": "Si alguno pecare por haber sido satisfecho bajo juramento, y fuere testigo que vio, o supo, y no lo denunciare, él llevará su pecado.",
        "Hebrews 6:16": "Porque los hombres ciertamente juran por uno mayor que ellos, y para ellos el fin de toda controversia es el juramento para confirmación.",
        "2 Corinthians 1:23": "Mas yo invoco a Dios por testigo sobre mi alma, que por ser indulgente con vosotros no he pasado todavía a Corinto.",
        "Deuteronomy 6:13": "A Jehová tu Dios temerás, y a él solo servirás, y por su nombre jurarás.",
        "Deuteronomy 10:20": "A Jehová tu Dios temerás, a él solo servirás, a él seguirás, y por su nombre jurarás.",
        "Deuteronomy 6:6-7": "Y estas palabras que yo te mando hoy, estarán sobre tu corazón; y las repetirás a tus hijos, y hablarás de ellas estando en tu casa, y andando por el camino, y al acostarte, y cuando te levantes.",
        "Hebrews 10:25": "No dejando de congregarnos, como algunos tienen por costumbre, sino exhortándonos; y tanto más, cuanto veis que aquel día se acerca.",
        "Acts 2:42": "Y perseveraban en la doctrina de los apóstoles, en la comunión unos con otros, en el partimiento del pan y en las oraciones.",
        "1 Corinthians 16:2": "Cada primer día de la semana cada uno de vosotros ponga aparte algo, según haya prosperado.",

        # Mandamientos 5-10
        "Ephesians 6:1-4": "Hijos, obedeced en el Señor a vuestros padres, porque esto es justo. Honra a tu padre y a tu madre, que es el primer mandamiento con promesa.",
        "Colossians 3:18-21": "Casadas, estad sujetas a vuestros maridos, como conviene en el Señor. Maridos, amad a vuestras mujeres, y no seáis ásperos con ellas. Hijos, obedeced a vuestros padres en todo, porque esto agrada al Señor. Padres, no exasperéis a vuestros hijos, para que no se desalienten.",
        "Proverbs 1:8": "Oye, hijo mío, la instrucción de tu padre, y no desprecies la dirección de tu madre.",
        "Romans 13:1-2": "Sométase toda persona a las autoridades superiores; porque no hay autoridad sino de parte de Dios, y las que hay, por Dios han sido establecidas.",
        "Exodus 20:12": "Honra a tu padre y a tu madre, para que tus días se alarguen en la tierra que Jehová tu Dios te da.",
        "Matthew 5:21-22": "Oísteis que fue dicho a los antiguos: No matarás; y cualquiera que matare será culpable de juicio. Pero yo os digo que cualquiera que se enoje contra su hermano, será culpable de juicio.",
        "Genesis 9:6": "El que derramare sangre de hombre, por el hombre su sangre será derramada; porque a imagen de Dios es hecho el hombre.",
        "Romans 13:4": "Porque es servidor de Dios para tu bien. Pero si haces lo malo, teme; porque no en vano lleva la espada.",
        "1 John 3:15": "Todo aquel que aborrece a su hermano es homicida; y sabéis que ningún homicida tiene vida eterna permanente en él.",
        "Romans 12:19": "No os venguéis vosotros mismos, amados míos, sino dejad lugar a la ira de Dios; porque escrito está: Mía es la venganza, yo pagaré, dice el Señor.",
        "Matthew 5:22": "Pero yo os digo que cualquiera que se enoje contra su hermano, será culpable de juicio.",
        "Matthew 5:44-45": "Pero yo os digo: Amad a vuestros enemigos, bendecid a los que os maldicen, haced bien a los que os aborrecen, y orad por los que os ultrajan y os persiguen; para que seáis hijos de vuestro Padre que está en los cielos.",
        "Romans 12:10": "Amaos los unos a los otros con amor fraternal; en cuanto a honra, prefiriéndoos los unos a los otros.",
        "Matthew 7:12": "Así que, todas las cosas que queráis que los hombres hagan con vosotros, así también haced vosotros con ellos; porque esto es la ley y los profetas.",
        "Galatians 6:1-2": "Hermanos, si alguno fuere sorprendido en alguna falta, vosotros que sois espirituales, restauradle con espíritu de mansedumbre. Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo.",
        "Ephesians 4:2": "Con toda humildad y mansedumbre, soportándoos con paciencia los unos a los otros en amor.",
        "1 Corinthians 6:18-20": "Huid de la fornicación. Cualquier otro pecado que el hombre cometa, está fuera del cuerpo; mas el que fornica, contra su propio cuerpo peca. ¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo?",
        "Hebrews 13:4": "Honroso sea en todos el matrimonio, y el lecho sin mancilla; pero a los fornicarios y a los adúlteros los juzgará Dios.",
        "Ephesians 5:3-4": "Pero fornicación y toda inmundicia, o avaricia, ni aun se nombre entre vosotros, como conviene a santos; ni palabras deshonestas, ni necedades, ni truhanerías, que no convienen.",
        "Matthew 5:27-28": "Oísteis que fue dicho: No cometerás adulterio. Pero yo os digo que cualquiera que mira a una mujer para codiciarla, ya adulteró con ella en su corazón.",
        "1 Thessalonians 4:3-5": "Pues la voluntad de Dios es vuestra santificación; que os apartéis de fornicación; que cada uno de vosotros sepa tener su propia esposa en santidad y honor.",
        "Ephesians 4:28": "El que hurtaba, no hurte más, sino trabaje, haciendo con sus manos lo que es bueno, para que tenga qué compartir con el que padece necesidad.",
        "Proverbs 11:1": "El peso falso es abominación a Jehová; mas la pesa cabal es su contentamiento.",
        "Luke 6:35": "Amad, pues, a vuestros enemigos, y haced bien, y prestad, no esperando de ello nada.",
        "Philippians 2:4": "No mirando cada uno por lo suyo propio, sino cada cual también por lo de los otros.",
        "1 Timothy 6:17-18": "A los ricos de este siglo manda que no sean altivos, ni pongan la esperanza en las riquezas, las cuales son inciertas, sino en el Dios vivo. Que hagan bien, que sean ricos en buenas obras, dadivosos, generosos.",
        "Ephesians 4:25": "Por lo cual, desechando la mentira, hablad verdad cada uno con su prójimo; porque somos miembros los unos de los otros.",
        "Proverbs 12:22": "Los labios mentirosos son abominación a Jehová; pero los que hacen verdad son su contentamiento.",
        "Matthew 7:1-2": "No juzguéis, para que no seáis juzgados. Porque con el juicio con que juzgáis, seréis juzgados.",
        "1 Peter 4:8": "Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados.",
        "Romans 7:7-8": "¿Qué diremos, pues? ¿La ley es pecado? En ninguna manera. Pero yo no conocí el pecado sino por la ley. Mas el pecado, tomando ocasión por el mandamiento, produjo en mí toda codicia.",
        "Proverbs 4:23": "Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.",
        "James 1:14-15": "Sino que cada uno es tentado, cuando de su propia concupiscencia es atraído y seducido. Entonces la concupiscencia, después que ha concebido, da a luz el pecado; y el pecado, siendo consumado, da a luz la muerte.",
        "Psalms 19:14": "Sean satisfechos los dichos de mi boca y la meditación de mi corazón delante de ti, oh Jehová, roca mía, y redentor mío.",
        "1 John 1:8": "Si decimos que no tenemos pecado, nos engañamos a nosotros mismos, y la verdad no está en nosotros.",
        "Romans 7:14-15": "Porque sabemos que la ley es espiritual; mas yo soy carnal, vendido al pecado. Porque lo que hago, no lo entiendo; pues no hago lo que quiero, sino lo que aborrezco, eso hago.",
        "Ecclesiastes 7:20": "Ciertamente no hay hombre justo en la tierra, que haga el bien y nunca peque.",
        "Philippians 3:12-14": "No que lo haya alcanzado ya, ni que ya sea perfecto; sino que prosigo, por ver si logro asir aquello para lo cual fui también asido por Cristo Jesús. Prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús.",
        "Psalms 51:2-4": "Lávame más y más de mi maldad, y límpiame de mi pecado. Porque yo reconozco mis rebeliones, y mi pecado está siempre delante de mí. Contra ti, contra ti solo he pecado, y he hecho lo malo delante de tus ojos.",

        # === PREGUNTAS 116-129 (Oración y Padre Nuestro) ===
        "Psalms 50:14-15": "Sacrifica a Dios alabanza, y paga tus votos al Altísimo. E invócame en el día de la angustia; te libraré, y tú me honrarás.",
        "1 Thessalonians 5:17": "Orad sin cesar.",
        "Matthew 7:7-8": "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá. Porque todo aquel que pide, recibe; y el que busca, halla; y al que llama, se le abrirá.",
        "Luke 11:9-13": "Y yo os digo: Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá. Pues si vosotros, siendo malos, sabéis dar buenas dádivas a vuestros hijos, ¿cuánto más vuestro Padre celestial dará el Espíritu Santo a los que se lo pidan?",
        "Romans 8:26": "Y de igual manera el Espíritu nos ayuda en nuestra debilidad; pues qué hemos de pedir como conviene, no lo sabemos, pero el Espíritu mismo intercede por nosotros con gemidos indecibles.",
        "1 John 5:14": "Y esta es la confianza que tenemos en él, que si pedimos alguna cosa conforme a su voluntad, él nos oye.",
        "John 14:13-14": "Y todo lo que pidiereis al Padre en mi nombre, lo haré, para que el Padre sea glorificado en el Hijo. Si algo pidiereis en mi nombre, yo lo haré.",
        "James 1:6": "Pero pida con fe, no dudando nada; porque el que duda es semejante a la onda del mar, que es arrastrada por el viento y echada de una parte a otra.",
        "Matthew 6:33": "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.",
        "James 1:17": "Toda buena dádiva y todo don perfecto desciende de lo alto, del Padre de las luces, en el cual no hay mudanza, ni sombra de variación.",
        "Philippians 4:6": "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias.",
        "Matthew 6:9-13": "Vosotros, pues, oraréis así: Padre nuestro que estás en los cielos, santificado sea tu nombre. Venga tu reino. Hágase tu voluntad, como en el cielo, así también en la tierra. El pan nuestro de cada día, dánoslo hoy. Y perdónanos nuestras deudas, como también nosotros perdonamos a nuestros deudores. Y no nos metas en tentación, mas líbranos del mal; porque tuyo es el reino, y el poder, y la gloria, por todos los siglos. Amén.",
        "Luke 11:2-4": "Y les dijo: Cuando oréis, decid: Padre nuestro que estás en los cielos, santificado sea tu nombre. Venga tu reino. Hágase tu voluntad, como en el cielo, así también en la tierra. El pan nuestro de cada día, dánoslo hoy. Y perdónanos nuestros pecados, porque también nosotros perdonamos a todos los que nos deben. Y no nos metas en tentación, mas líbranos del mal.",
        "Matthew 7:9-11": "¿Qué hombre hay de vosotros, que si su hijo le pide pan, le dará una piedra? ¿O si le pide un pescado, le dará una serpiente? Pues si vosotros, siendo malos, sabéis dar buenas dádivas a vuestros hijos, ¿cuánto más vuestro Padre que está en los cielos dará buenas cosas a los que le pidan?",
        "Luke 11:11-13": "¿Qué padre de vosotros, si su hijo le pide pan, le dará una piedra? ¿o si pescado, en lugar de pescado, le dará una serpiente? Pues si vosotros, siendo malos, sabéis dar buenas dádivas a vuestros hijos, ¿cuánto más vuestro Padre celestial dará el Espíritu Santo a los que se lo pidan?",
        "Matthew 6:9": "Vosotros, pues, oraréis así: Padre nuestro que estás en los cielos, santificado sea tu nombre.",
        "Psalms 115:1": "No a nosotros, oh Jehová, no a nosotros, sino a tu nombre da gloria, por tu misericordia, por tu verdad.",
        "Romans 2:24": "Porque como está escrito, el nombre de Dios es blasfemado entre los gentiles por causa de vosotros.",
        "Psalms 2:6-9": "Pero yo he puesto mi rey sobre Sion, mi santo monte. Yo publicaré el decreto; Jehová me ha dicho: Mi hijo eres tú; yo te engendré hoy. Pídeme, y te daré por herencia las naciones, y como posesión tuya los confines de la tierra.",
        "Romans 10:1": "Hermanos, ciertamente el anhelo de mi corazón, y mi oración a Dios por Israel, es para salvación.",
        "Colossians 1:9-12": "Por lo cual también nosotros, desde el día que lo oímos, no cesamos de orar por vosotros, y de pedir que seáis llenos del conocimiento de su voluntad en toda sabiduría e inteligencia espiritual.",
        "Revelation 22:17-20": "Y el Espíritu y la Esposa dicen: Ven. Y el que oye, diga: Ven. El que da testimonio de estas cosas dice: Ciertamente vengo en breve. Amén; sí, ven, Señor Jesús.",
        "Matthew 6:10": "Venga tu reino. Hágase tu voluntad, como en el cielo, así también en la tierra.",
        "Matthew 16:24": "Entonces Jesús dijo a sus discípulos: Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz, y sígame.",
        "Titus 2:11-12": "Porque la gracia de Dios se ha manifestado para salvación a todos los hombres, enseñándonos que, renunciando a la impiedad y a los deseos mundanos, vivamos en este siglo sobria, justa y piadosamente.",
        "Matthew 6:11": "El pan nuestro de cada día, dánoslo hoy.",
        "Psalms 104:27-28": "Todos ellos esperan en ti, para que les des su comida a su tiempo. Les das, recogen; abres tu mano, se sacian de bien.",
        "Psalms 145:15-16": "Los ojos de todos esperan en ti, y tú les das su comida a su tiempo. Abres tu mano, y satisfaces el deseo de todo ser viviente.",
        "Proverbs 30:8": "Vanidad y palabra mentirosa aparta de mí; no me des pobreza ni riquezas; mantenme del pan necesario.",
        "1 Timothy 4:4-5": "Porque todo lo que Dios creó es bueno, y nada es de desecharse, si se toma con acción de gracias; porque por la palabra de Dios y por la oración es santificado.",
        "Matthew 6:12": "Y perdónanos nuestras deudas, como también nosotros perdonamos a nuestros deudores.",
        "Psalms 51:1-4": "Ten piedad de mí, oh Dios, conforme a tu misericordia; conforme a la multitud de tus piedades borra mis rebeliones. Lávame más y más de mi maldad, y límpiame de mi pecado. Contra ti, contra ti solo he pecado.",
        "1 John 2:1-2": "Hijitos míos, estas cosas os escribo para que no pequéis; y si alguno hubiere pecado, abogado tenemos para con el Padre, a Jesucristo el justo. Y él es la propiciación por nuestros pecados.",
        "Matthew 6:14-15": "Porque si perdonáis a los hombres sus ofensas, os perdonará también a vosotros vuestro Padre celestial; mas si no perdonáis a los hombres sus ofensas, tampoco vuestro Padre os perdonará vuestras ofensas.",
        "Ephesians 4:32": "Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros, como Dios también os perdonó a vosotros en Cristo.",
        "Matthew 6:13": "Y no nos metas en tentación, mas líbranos del mal; porque tuyo es el reino, y el poder, y la gloria, por todos los siglos. Amén.",
        "Matthew 26:41": "Velad y orad, para que no entréis en tentación; el espíritu a la verdad está dispuesto, pero la carne es débil.",
        "1 Peter 5:8": "Sed sobrios, y velad; porque vuestro adversario el diablo, como león rugiente, anda alrededor buscando a quien devorar.",
        "John 17:15": "No ruego que los quites del mundo, sino que los guardes del mal.",
        "Ephesians 6:10-13": "Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza. Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.",
        "1 Corinthians 10:13": "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar.",
        "Romans 10:11-12": "Pues la Escritura dice: Todo aquel que en él creyere, no será avergonzado. Porque no hay diferencia entre judío y griego, pues el mismo que es Señor de todos, es rico para con todos los que le invocan.",
        "2 Peter 2:9": "Sabe el Señor librar de tentación a los piadosos, y reservar a los injustos para ser castigados en el día del juicio.",
        "Psalms 55:22": "Echa sobre Jehová tu carga, y él te sustentará; no dejará para siempre caído al justo.",
        "2 Timothy 4:18": "Y el Señor me librará de toda obra mala, y me preservará para su reino celestial. A él sea gloria por los siglos de los siglos. Amén.",
        "2 Corinthians 1:20": "Porque todas las promesas de Dios son en él Sí, y en él Amén, por medio de nosotros, para la gloria de Dios.",
        "2 Timothy 2:13": "Si fuéremos infieles, él permanece fiel; él no puede negarse a sí mismo.",
        "Psalms 145:18": "Cercano está Jehová a todos los que le invocan, a todos los que le invocan de veras.",
        "Psalms 145:18-19": "Cercano está Jehová a todos los que le invocan, a todos los que le invocan de veras. Cumplirá el deseo de los que le temen; oirá asimismo el clamor de ellos, y los salvará.",
        "Revelation 22:20": "El que da testimonio de estas cosas dice: Ciertamente vengo en breve. Amén; sí, ven, Señor Jesús.",

        # Extras
        "Proverbs 25:21-22": "Si el que te aborrece tuviere hambre, dale de comer pan, y si tuviere sed, dale de beber agua; porque ascuas amontonarás sobre su cabeza, y Jehová te lo pagará.",
        "Matthew 26:52": "Entonces Jesús le dijo: Vuelve tu espada a su lugar; porque todos los que tomen espada, a espada perecerán.",
        "Proverbs 14:30": "El corazón apacible es vida de la carne; mas la envidia es carcoma de los huesos.",
        "Proverbs 28:8": "El que aumenta sus riquezas con usura y crecido interés, para aquel que se compadece de los pobres las aumenta.",
        "Proverbs 11:13": "El que anda en chismes descubre el secreto; mas el de espíritu fiel lo guarda todo.",
        "Exodus 34:13-14": "Derribaréis sus altares, y quebraréis sus estatuas, y cortaréis sus imágenes de Asera. Porque no te has de inclinar a ningún otro dios, pues Jehová, cuyo nombre es Celoso, Dios celoso es.",
        "Deuteronomy 7:5": "Mas así habéis de hacer con ellos: sus altares destruiréis, y quebraréis sus estatuas, y destruiréis sus imágenes de Asera, y quemaréis sus esculturas en el fuego.",
        "2 Kings 18:4": "El quitó los lugares altos, y quebró las imágenes, y cortó los símbolos de Asera, e hizo pedazos la serpiente de bronce que había hecho Moisés.",
        "Isaiah 48:1": "Oíd esto, casa de Jacob, que os llamáis del nombre de Israel, los que salieron de las aguas de Judá, los que juran en el nombre de Jehová.",
        "Psalms 40:9-10": "He anunciado justicia en grande congregación; he aquí, no refrené mis labios, Jehová, tú lo sabes.",
        "Colossians 3:18-21": "Casadas, estad sujetas a vuestros maridos, como conviene en el Señor. Hijos, obedeced a vuestros padres en todo, porque esto agrada al Señor.",
    }

    cursor.executemany(
        "INSERT OR REPLACE INTO biblia (referencia, texto) VALUES (?, ?)",
        list(textos.items())
    )

    conn.commit()
    conn.close()
    print(f"Textos bíblicos insertados: {len(textos)} versículos")

if __name__ == "__main__":
    crear_tabla_biblia()
